<h1><center>Churn Prediction (Statistical Testing, Stacking Ensemble) </center></h1>

<center><img src="https://uploads-ssl.webflow.com/60d45d63543dd9baaad4cb28/60d85fd90743e2299c711be5_1%20dqSLRSEC2GDV9bw_PplCYQ.png" align="center"/></center>

<a id='8'></a>

# 8 Feature Engineering

For classification generally these methods are used: chi2, f_classif, mutual_info_classif

* **chi2**: Computes chi-squared stats between each non-negative feature and class. This score can be used to select the n_features features with the highest values for the test chi-squared statistic from X, which must contain only non-negative features such as booleans or frequencies (e.g., term counts in document classification), relative to the classes.

* **f_classif**: Compute the ANOVA F-value for the provided sample.

* **mutual_info_classif**: Estimates mutual information for a discrete target variable. Mutual information (MI) between two random variables is a non-negative value, which measures the dependency between the variables. It is equal to zero if and only if two random variables are independent, and higher values mean higher dependency.

source= https://scikit-learn.org/stable/modules/feature_selection.html




**N.B** : I may apply One Hot Encoding for the categorical columns, But to compare the correlation results obtained from previous notebook with model feature importance I am keeping the feature set as it is ,applying only ordinal encoding

In [90]:
# 1) Start from original
df_churn_cleaned = df_churn.copy()

# (optional) drop features you don't want
# df_churn_cleaned.drop(['gender','Partner','PhoneService','MultipleLines','StreamingMovies'], axis=1, inplace=True)

# 2) One-hot encode
df_churn_ohe = pd.get_dummies(df_churn_cleaned, drop_first=False)

# 3) Safely drop dummy cols that may or may not exist
cols_to_drop = [
    'MultipleLines_No phone service',
    'OnlineSecurity_No internet service',
    'OnlineBackup_No internet service',
    'DeviceProtection_No internet service',
    'TechSupport_No internet service',
    'StreamingTV_No internet service',
    'StreamingMovies_No internet service'
]
df_churn_ohe.drop(columns=cols_to_drop, errors='ignore', inplace=True)

df_churn_ohe.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,tenure-binned_Medium,tenure-binned_High,MonthlyCharges-binned_Low,MonthlyCharges-binned_Medium,MonthlyCharges-binned_High,TotalCharges-binned_Low,TotalCharges-binned_Medium,TotalCharges-binned_High,Churn_No,Churn_Yes
0,0,1,29.85,29.85,True,False,False,True,True,False,...,False,False,True,False,False,True,False,False,True,False
1,0,34,56.95,1889.50,False,True,True,False,True,False,...,True,False,False,True,False,True,False,False,True,False
2,0,2,53.85,108.15,False,True,True,False,True,False,...,False,False,False,True,False,True,False,False,False,True
3,0,45,42.30,1840.75,False,True,True,False,True,False,...,True,False,True,False,False,True,False,False,True,False
4,0,2,70.70,151.65,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,True

<a id='8.1'></a>
## 8.1 Encode Target variable

In [91]:
df_churn_cleaned = df_churn.copy()
df_churn_cleaned.Churn[df_churn_cleaned.Churn.str.lower() == 'yes'] = 1
df_churn_cleaned.Churn[df_churn_cleaned.Churn.str.lower() == 'no'] = 0

df_churn_cleaned['Churn'] = df_churn_cleaned['Churn'].astype('float')

In [92]:
df_churn_cleaned.to_csv("Telco-Customer-Churn-dataset-cleaned.csv", index=False)

In [93]:
printmd("**Column Info**")
display(df_churn_cleaned.info())
printmd("<br>**Datatypes Count**")
display(df_churn.dtypes.value_counts())
printmd("<br>**Categorical Features**")
display(df_churn.describe(include=['object']).T)

**Column Info**

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 7043 non-null   object
 1   SeniorCitizen          7043 non-null   int64
 2   Partner                7043 non-null   object
 3   Dependents             7043 non-null   object
 4   tenure                 7043 non-null   int64
 5   PhoneService           7043 non-null   object
 6   MultipleLines          7043 non-null   object
 7   InternetService        7043 non-null   object
 8   OnlineSecurity         7043 non-null   object
 9   OnlineBackup           7043 non-null   object
 10  DeviceProtection       7043 non-null   object
 11  TechSupport            7043 non-null   object
 12  StreamingTV            7043 non-null   object
 13  StreamingMovies        7043 non-null   object
 14  Contract               7043 non-null   object
 15  PaperlessBilling       7043 non-null   object
 16  PaymentMethod          7043 non-null   object
 17  MonthlyCharges         7043 non-null   float64
 18  TotalCharges           7043 non-null   float64
 19  tenure-binned          7043 non-null   category
 20  MonthlyCharges-binned  7043 non-null   category
 21  TotalCharges-binned    7043 non-null   category
 22  Churn                  7043 non-null   float64
dtypes: category(3), float64(3), int64(2), object(15)
memory usage: 1.1+ MB

None

<br>**Datatypes Count**

object      16
category     3
int64        2
float64      2
Name: count, dtype: int64

<br>**Categorical Features**

                 count unique               top  freq
gender            7043      2              Male  3555
Partner           7043      2                No  3641
Dependents        7043      2                No  4933
PhoneService      7043      2               Yes  6361
MultipleLines     7043      3                No  3390
InternetService   7043      3       Fiber optic  3096
OnlineSecurity    7043      3                No  3498
OnlineBackup      7043      3                No  3088
DeviceProtection  7043      3                No  3095
TechSupport       7043      3                No  3473
StreamingTV       7043      3                No  2810
StreamingMovies   7043      3                No  2785
Contract          7043      3    Month-to-month  3875
PaperlessBilling  7043      2               Yes  4171
PaymentMethod     7043      4  Electronic check  2365
Churn             7043      2                No  5174